    aws_access_key: 
    aws_secret_key:
    key_name: POC.pem
    aws_region: us-east
    vpc_id: vpc-779a591f
    ami_id: ami-82f4dae7
    instance_type: t2.micro
    #my_local_cidr_ip: <enter cidr_ip>
